### PR TITLE
Onboarding overflow

### LINKED ISSUE #205: Content Overflow on Onboarding Screens
**Describe the bug**

### PR DESCRIPTION
**Pull request by SebastianWagner2**
Closes #205 

Note that contents can still overflow toward the bottom of the screen but take considerarbly more text to do so now.

Since the implementation of the onboarding screen contents was changed to a stack, UI elements can now be on top of each other. If the text gets too long, it might conceal the page indicators.

---

### CODE REVIEW

File: app/lib/onboarding/pages/onboarding.dart [hunk 1]
```diff
@@ -7,6 +7,39 @@ import 'package:flutter_svg/flutter_svg.dart';
 import '../../../common/module.dart';
 import '../../../common/routing/router.dart';
 
+const pagesCount = 3;
```
Comment (Benjamin-Frost) [inline app/lib/onboarding/pages/onboarding.dart:10]:
```suggestion
const _pagesCount = 3;
```

File: app/lib/onboarding/pages/onboarding.dart [hunk 2]
```diff
@@ -16,50 +49,106 @@ class OnboardingPage extends HookWidget {
...
+    required this.imagePath,
+    required this.getHeader,
+    required this.getText,
+  }) : super(key: key);
+
+  final PageController pageController;
+  final ValueNotifier<int> currentPage;
+  final String imagePath;
+  final Set<String> Function(BuildContext) getHeader;
+  final Set<String> Function(BuildContext) getText;
```
Comment (Benjamin-Frost) [inline app/lib/onboarding/pages/onboarding.dart:75]: Why didn't you simply make these `String`s?

File: app/lib/onboarding/pages/onboarding.dart [hunk 3]
```diff
@@ -16,50 +49,106 @@ class OnboardingPage extends HookWidget {
...
   }
 
   List<Widget> _buildPageIndicator(BuildContext context, int currentPage) {
     final list = <Widget>[];
-    for (var i = 0; i < _pages.length; ++i) {
-      list.add(i == currentPage ? _indicator(context, true) : _indicator(context, false));
+    for (var i = 0; i < pagesCount; ++i) {
+      list.add(i == currentPage
+          ? _indicator(context, true)
+          : _indicator(context, false));
```
Comment (Benjamin-Frost) [inline app/lib/onboarding/pages/onboarding.dart:151]:
```suggestion
      list.add(_indicator(context, i == currentPage));
```

**Review by Benjamin-Frost — CHANGES_REQUESTED** [review]

File: app/lib/onboarding/pages/onboarding.dart (hunk 1 above)
Comment (Benjamin-Frost) [reply app/lib/onboarding/pages/onboarding.dart:10]: Also, I don't like having this extra variable in general. There is not a single source of truth with this in place

**Review by Benjamin-Frost — APPROVED** [review]
Really well done 🚀
